import { createSlice } from "@reduxjs/toolkit";
// Fetch initial state from localStorage or set it to an empty array if localStorage is empty
const initialState = JSON.parse(localStorage.getItem('cart')) ?? [];
// Create a slice of the Redux store for cart management
const cartSlice = createSlice({
    name: 'cart', // Name of the slice
    initialState, // Initial state for the slice
    reducers : {
      
        addToCart(state, action){
              // Reducer function to add an item to the cart
            state.push(action.payload)      // Pushes the new item into the cart array      
        },
        deleteFromCart(state,action){
            // Reducer function to delete an item from the cart
            return state.filter(item => item.id != action.payload.id);
            // Returns a new array excluding the item with the matching ID from the cart
        }
    }
})
// Extract the action creators generated by createSlice for addToCart and deleteFromCart
export const {addToCart, deleteFromCart} = cartSlice.actions;
// Export the reducer generated by createSlice to manage the cart state
export default cartSlice.reducer;







